### ISSUE TITLE
Java unsupported exception on CDH 5.12

### ISSUE THREAD

**Issue by pieterjanverbruggen** [jshmain/log-analytics#1]
I followed the tutorial and used the code as on GitHub, unfortunately when I run the code I get the error below. Basically it failes when I run

`solrServer.request(req)`

I am running Cloudera 5.12 and using SolrJ 4.10.3-5.12.1

> Caused by: java.lang.UnsupportedOperationException
>         at java.util.AbstractList.remove(AbstractList.java:161)
>         at java.util.AbstractList$Itr.remove(AbstractList.java:374)
>         at java.util.AbstractList.removeRange(AbstractList.java:571)
>         at java.util.AbstractList.clear(AbstractList.java:234)
>         at SolRSupport$.sendBatchToSolr(SolRSupport.scala:81)
>         at SolRSupport$$anonfun$indexDoc$1$$anonfun$apply$1.apply(SolRSupport.scala:37)
>         at SolRSupport$$anonfun$indexDoc$1$$anonfun$apply$1.apply(SolRSupport.scala:37)
>         at scala.collection.Iterator$class.foreach(Iterator.scala:893)
>         at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
>         at SolRSupport$$anonfun$indexDoc$1.apply(SolRSupport.scala:37)
>         at SolRSupport$$anonfun$indexDoc$1.apply(SolRSupport.scala:35)
>         at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
>         at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:926)
>         at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
>         at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2062)
>         at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
>         at org.apache.spark.scheduler.Task.run(Task.scala:108)
>         at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)
>

**Comment by pieterjanverbruggen** [comment]
Just noticed that this error comes when batch.clear() is called.. So advice for people running on Scala 2.11 with Spark2: remove the batch clear..
